#!/bin/bash
# Cleanup duplicate and unused specification keys
# IMPORTANT: Run check_duplicate_specs.sql first to identify which keys are actually used

echo "=== Specification Keys Cleanup Report ==="
echo ""
echo "DUPLICATES IDENTIFIED:"
echo "========================"
echo ""
echo "1. WARRANTY GROUP (Same Meaning):"
echo "   - ID 161: 'Warranty Period'"
echo "   - ID 509: 'Warranty Period (Years)' ← NEWER (2025-11-17)"
echo "   - ID 510: 'Warranty Coverage' (Different, but related)"
echo "   ACTION: Use ID 509 'Warranty Period (Years)' as it's more specific"
echo ""
echo "2. NETWORK SERVICE GROUP (Service Available):"
echo "   - ID 453: '2G Service Available' (2025-11-16)"
echo "   - ID 454: '3G Service Available' (2025-11-16)"
echo "   - ID 456: '5G Service Available' (2025-11-16)"
echo "   - Also have: '4G/LTE Service Available' (ID 455)"
echo "   ACTION: Keep all if used for telecom products, delete if not"
echo ""
echo "3. CHARGING SPECIFICATION:"
echo "   - ID 18: 'Charging Speed'"
echo "   - ID 553: 'fast_charging' (2025-11-20) ← Lowercase, duplicate"
echo "   ACTION: Delete ID 553 'fast_charging', use ID 18 'Charging Speed'"
echo ""
echo "4. OTHER DUPLICATES TO CHECK:"
echo "   - 'Warranty' (ID 323) vs 'Warranty Period' (ID 161)"
echo "   - Network-related keys that might be redundant"
echo ""
echo ""
echo "NEXT STEPS:"
echo "==========="
echo "1. Run: psql -h localhost -p 5428 -U root -d kossti < check_duplicate_specs.sql"
echo "2. Review the output to see which keys have actual data"
echo "3. Create migration to:"
echo "   - Migrate data from unused keys to canonical keys"
echo "   - Delete unused specification keys"
echo "   - Update foreign keys in specifications table"
echo ""
echo "CLEANUP QUERIES (After verifying usage):"
echo "========================================"
echo ""
echo "-- Option 1: Delete completely unused keys"
echo "DELETE FROM specification_keys WHERE id IN (553) AND id NOT IN (SELECT DISTINCT specification_key_id FROM specifications);"
echo ""
echo "-- Option 2: Migrate data from one key to another (if needed)"
echo "UPDATE specifications SET specification_key_id = 509 WHERE specification_key_id = 161;"
echo "DELETE FROM specification_keys WHERE id = 161 AND id NOT IN (SELECT DISTINCT specification_key_id FROM specifications);"
echo ""
echo "-- Option 3: Check for orphaned keys (no usage)"
echo "SELECT sk.id, sk.specification_key"
echo "FROM specification_keys sk"
echo "LEFT JOIN specifications s ON sk.id = s.specification_key_id"
echo "WHERE s.id IS NULL"
echo "ORDER BY sk.id;"
