package seeders

// DefaultMobileSpecs returns a comprehensive set of mobile phone specification keys
// with safe default values. Seeders can call this and override model-specific values.
func DefaultMobileSpecs() map[string]string {
	return map[string]string{
		"Display Size":                  "",
		"Processor":                     "",
		"Chipset":                       "",
		"Cpu Type":                      "",
		"Gpu Type":                      "",
		"Ram":                           "",
		"Storage":                       "",
		"Display Type":                  "",
		"Resolution":                    "",
		"Screen Protection":             "",
		"Refresh Rate":                  "",
		"Build Material":                "",
		"Weight":                        "",
		"Dimensions":                    "",
		"Water Resistance":              "",
		"Network Technology":            "",
		"2g Bands":                      "",
		"3g Bands":                      "",
		"4g Bands":                      "",
		"5g Bands":                      "",
		"Wifi Support":                  "",
		"Bluetooth Version":             "",
		"Nfc Support":                   "",
		"Usb Type":                      "",
		"Rear Camera":                   "",
		"Camera Features":               "",
		"Quad Camera Setup":             "",
		"Camera Video Resolution":       "",
		"Optical Zoom":                  "",
		"Front Camera":                  "",
		"Front Camera Video Resolution": "",
		"Operating System":              "",
		"Battery":                       "",
		"Battery Type":                  "",
		"Fast Charging":                 "",
		"Charging Speed":                "",
		"Wireless Charging":             "",
		"5g Support":                    "",
		"Positioning System":            "",
		"Sensors":                       "",
		"Special Features":              "",
		"Sim Card Type":                 "",
		"Loudspeaker Quality":           "",
		"Audio Quality":                 "",
		"Audio Jack":                    "",
		"Available Colors":              "",
		"Announcement Date":             "",
		"Device Status":                 "",
		"Internal Memory Capacity":      "",
		"Card Slot Type":                "",
		"Sar Rating":                    "",
		"Sar Rating Eu":                 "",
		"Model Variants":                "",
		"Processor Speed":               "",
	}
}
