-- SQL query to check if specifications exist in the database
SELECT specification_key
FROM specification_keys
WHERE specification_key IN (
    'Engine Type',
    'Fuel Efficiency (km/l)',
    'Transmission Type',
    'Seating Capacity',
    'Airbags',
    'ABS (Anti-lock Braking System)',
    'Infotainment System',
    'Cruise Control',
    'Parking Sensors',
    'Rear Camera',
    'Sunroof',
    'Ground Clearance (mm)',
    'Boot Space (liters)',
    'Warranty Period (Years)',
    'Price (BDT)',
    'Availability in Bangladesh',
    'After-Sales Service',
    'Return / Exchange Policy',
    'Brand',
    'Model',
    'Year',
    'Body Type',
    'Engine Displacement (cc)',
    'Cylinders',
    'Max Power (hp)',
    'Max Torque (Nm)',
    'City Fuel Economy (km/l)',
    'Highway Fuel Economy (km/l)',
    'Combined Fuel Economy (km/l)',
    'Fuel Tank Capacity (l)',
    'Length (mm)',
    'Width (mm)',
    'Height (mm)',
    'Wheelbase (mm)',
    'Drive Type',
    'AC Type',
    'Power Windows',
    'Power Steering',
    'Seat Material',
    'Driver Airbag',
    'Passenger Airbag',
    'Side Airbags',
    'Curtain Airbags',
    'Camera',
    'Child Safety Lock',
    'Stability Control',
    'Service Interval (km)',
    'Spare Parts Availability',
    'Estimated Annual Maintenance Cost (BDT)',
    'Registration Cost (BDT)',
    'Insurance Cost (BDT)'
);