-- SQL query to insert missing specification keys into the specification_keys table
INSERT INTO specification_keys (specification_key)
VALUES
    ('Fuel Efficiency (km/l)'),
    ('Transmission Type'),
    ('Engine Displacement (cc)'),
    ('Cylinders'),
    ('Max Power (hp)'),
    ('Max Torque (Nm)'),
    ('City Fuel Economy (km/l)'),
    ('Highway Fuel Economy (km/l)'),
    ('Combined Fuel Economy (km/l)'),
    ('Fuel Tank Capacity (l)'),
    ('Length (mm)'),
    ('Width (mm)'),
    ('Height (mm)'),
    ('Wheelbase (mm)'),
    ('AC Type'),
    ('Power Windows'),
    ('Seat Material'),
    ('Driver Airbag'),
    ('Passenger Airbag'),
    ('Side Airbags'),
    ('Curtain Airbags'),
    ('Camera'),
    ('Child Safety Lock'),
    ('Stability Control'),
    ('Service Interval (km)'),
    ('Spare Parts Availability'),
    ('Estimated Annual Maintenance Cost (BDT)'),
    ('Registration Cost (BDT)'),
    ('Insurance Cost (BDT)')
ON CONFLICT (specification_key) DO NOTHING;

-- SQL query to insert translations for the missing specification keys into the specification_translations table
INSERT INTO specification_translations (specification_key, language, translation)
VALUES
    ('Fuel Efficiency (km/l)', 'en', 'Fuel Efficiency (km/l)'),
    ('Transmission Type', 'en', 'Transmission Type'),
    ('Engine Displacement (cc)', 'en', 'Engine Displacement (cc)'),
    ('Cylinders', 'en', 'Cylinders'),
    ('Max Power (hp)', 'en', 'Max Power (hp)'),
    ('Max Torque (Nm)', 'en', 'Max Torque (Nm)'),
    ('City Fuel Economy (km/l)', 'en', 'City Fuel Economy (km/l)'),
    ('Highway Fuel Economy (km/l)', 'en', 'Highway Fuel Economy (km/l)'),
    ('Combined Fuel Economy (km/l)', 'en', 'Combined Fuel Economy (km/l)'),
    ('Fuel Tank Capacity (l)', 'en', 'Fuel Tank Capacity (l)'),
    ('Length (mm)', 'en', 'Length (mm)'),
    ('Width (mm)', 'en', 'Width (mm)'),
    ('Height (mm)', 'en', 'Height (mm)'),
    ('Wheelbase (mm)', 'en', 'Wheelbase (mm)'),
    ('AC Type', 'en', 'AC Type'),
    ('Power Windows', 'en', 'Power Windows'),
    ('Seat Material', 'en', 'Seat Material'),
    ('Driver Airbag', 'en', 'Driver Airbag'),
    ('Passenger Airbag', 'en', 'Passenger Airbag'),
    ('Side Airbags', 'en', 'Side Airbags'),
    ('Curtain Airbags', 'en', 'Curtain Airbags'),
    ('Camera', 'en', 'Camera'),
    ('Child Safety Lock', 'en', 'Child Safety Lock'),
    ('Stability Control', 'en', 'Stability Control'),
    ('Service Interval (km)', 'en', 'Service Interval (km)'),
    ('Spare Parts Availability', 'en', 'Spare Parts Availability'),
    ('Estimated Annual Maintenance Cost (BDT)', 'en', 'Estimated Annual Maintenance Cost (BDT)'),
    ('Registration Cost (BDT)', 'en', 'Registration Cost (BDT)'),
    ('Insurance Cost (BDT)', 'en', 'Insurance Cost (BDT)')
ON CONFLICT (specification_key, language) DO NOTHING;