package seeders

import (
	"kossti/internal/domain/entities"
	"kossti/internal/infrastructure/database/models"

	"gorm.io/gorm"
)

// BrandSeeder handles seeding brands
type BrandSeeder struct {
	BaseSeeder
}

// NewBrandSeeder creates a new brand seeder
func NewBrandSeeder() *BrandSeeder {
	return &BrandSeeder{
		BaseSeeder: BaseSeeder{name: "Brands"},
	}
}

// Seed implements the Seeder interface
func (bs *BrandSeeder) Seed(db *gorm.DB) error {
	brands := []struct {
		Name   string
		Slug   string
		Status int
	}{
		// International Brands - Technology & Electronics
		{"Abercrombie & Fitch", "abercrombie-fitch", 1},
		{"Acer", "acer", 1},
		{"Adidas", "adidas", 1},
		{"Airbus", "airbus", 1},
		{"Alcatel", "alcatel", 1},
		{"Allianz", "allianz", 1},
		{"Amazon", "amazon", 1},
		{"AMD", "amd", 1},
		{"American Express", "american-express", 1},
		{"Apple", "apple", 1},
		{"Arla", "arla", 1},
		{"Armani", "armani", 1},
		{"Asus", "asus", 1},
		{"Aston Martin", "aston-martin", 1},
		{"Audi", "audi", 1},
		{"Avon", "avon", 1},

		// B Brands
		{"Baidu", "baidu", 1},
		{"Benelli", "benelli", 1},
		{"Bajaj", "bajaj", 1},
		{"Balenciaga", "balenciaga", 1},
		{"Barclays", "barclays", 1},
		{"Bata", "bata", 1},
		{"Beats", "beats", 1},
		{"Ben & Jerry's", "ben-jerry-s", 1},
		{"Bentley", "bentley", 1},
		{"Blackberry", "blackberry", 1},
		{"Blackview", "blackview", 1},
		{"BMW", "bmw", 1},
		{"Bosch", "bosch", 1},
		{"Bose", "bose", 1},
		{"Bottega Veneta", "bottega-veneta", 1},
		{"Braun", "braun", 1},
		{"Bridgestone", "bridgestone", 1},
		{"Brother", "brother", 1},
		{"Budweiser", "budweiser", 1},
		{"Bugatti", "bugatti", 1},
		{"Bulgari", "bulgari", 1},
		{"Burberry", "burberry", 1},

		// C Brands
		{"Cadbury", "cadbury", 1},
		{"Cadillac", "cadillac", 1},
		{"Calvin Klein", "calvin-klein", 1},
		{"Canon", "canon", 1},
		{"Carlsberg", "carlsberg", 1},
		{"Cartier", "cartier", 1},
		{"Casio", "casio", 1},
		{"CAT", "cat", 1},
		{"Chanel", "chanel", 1},
		{"Chevrolet", "chevrolet", 1},
		{"Chivas Regal", "chivas-regal", 1},
		{"Cisco", "cisco", 1},
		{"Citizen", "citizen", 1},
		{"Clarins", "clarins", 1},
		{"Clinique", "clinique", 1},
		{"Coach", "coach", 1},
		{"Coca-Cola", "coca-cola", 1},
		{"Colgate", "colgate", 1},
		{"Converse", "converse", 1},
		{"Cooper's", "cooper-s", 1},
		{"Corona", "corona", 1},
		{"Crocs", "crocs", 1},
		{"Cubot", "cubot", 1},

		// D Brands
		{"Daewoo", "daewoo", 1},
		{"Daihatsu", "daihatsu", 1},
		{"Daikin", "daikin", 1},
		{"Danone", "danone", 1},
		{"Deckard", "deckard", 1},
		{"Dell", "dell", 1},
		{"DHL", "dhl", 1},
		{"Diesel", "diesel", 1},
		{"Dior", "dior", 1},
		{"Disney", "disney", 1},
		{"Dodge", "dodge", 1},
		{"Dolce & Gabbana", "dolce-gabbana", 1},
		{"Doogee", "doogee", 1},
		{"Dove", "dove", 1},
		{"Dr. Martens", "dr-martens", 1},
		{"Dropbox", "dropbox", 1},
		{"Ducati", "ducati", 1},
		{"Dunlop", "dunlop", 1},
		{"Duracell", "duracell", 1},

		// E Brands
		{"eBay", "ebay", 1},
		{"Electrolux", "electrolux", 1},
		{"Emirates", "emirates", 1},
		{"Energizer", "energizer", 1},
		{"Epson", "epson", 1},
		{"Ericsson", "ericsson", 1},
		{"Estée Lauder", "estee-lauder", 1},

		// F Brands
		{"Facebook", "facebook", 1},
		{"Fairphone", "fairphone", 1},
		{"Fanta", "fanta", 1},
		{"FedEx", "fedex", 1},
		{"Fendi", "fendi", 1},
		{"Ferrari", "ferrari", 1},
		{"Ferrero", "ferrero", 1},
		{"Fiat", "fiat", 1},
		{"Fila", "fila", 1},
		{"Fitbit", "fitbit", 1},
		{"Ford", "ford", 1},
		{"Fossil", "fossil", 1},
		{"Fujifilm", "fujifilm", 1},

		// G Brands
		{"GAP", "gap", 1},
		{"Garmin", "garmin", 1},
		{"Gatorade", "gatorade", 1},
		{"GE", "ge", 1},
		{"General Motors", "general-motors", 1},
		{"Geox", "geox", 1},
		{"Gillette", "gillette", 1},
		{"Givenchy", "givenchy", 1},
		{"Glenfiddich", "glenfiddich", 1},
		{"GMC", "gmc", 1},
		{"Godrej", "godrej", 1},
		{"GoPro", "gopro", 1},
		{"Google", "google", 1},
		{"Goodyear", "goodyear", 1},
		{"Gucci", "gucci", 1},
		{"Guess", "guess", 1},

		// H Brands
		{"H&M", "h-m", 1},
		{"Haier", "haier", 1},
		{"Hero", "hero", 1},
		{"Harley-Davidson", "harley-davidson", 1},
		{"Havaianas", "havaianas", 1},
		{"Heineken", "heineken", 1},
		{"Heinz", "heinz", 1},
		{"Hermès", "hermes", 1},
		{"Hershey's", "hershey-s", 1},
		{"Hewlett-Packard", "hewlett-packard", 1},
		{"Hilton", "hilton", 1},
		{"Hitachi", "hitachi", 1},
		{"Hisense", "hisense", 1},
		{"Honda", "honda", 1},
		{"Honor", "honor", 1},
		{"HTC", "htc", 1},
		{"Huawei", "huawei", 1},
		{"Hugo Boss", "hugo-boss", 1},
		{"Hunter", "hunter", 1},
		{"Hyundai", "hyundai", 1},

		// I Brands
		{"IBM", "ibm", 1},
		{"IKEA", "ikea", 1},
		{"Infinix", "infinix", 1},
		{"Intel", "intel", 1},
		{"Itel", "itel", 1},

		// J Brands
		{"Jack Daniel's", "jack-daniel-s", 1},
		{"Jaguar", "jaguar", 1},
		{"Jameson", "jameson", 1},
		{"JBL", "jbl", 1},
		{"Jeep", "jeep", 1},
		{"JioPhone", "jiophone", 1},
		{"Johnson & Johnson", "johnson-johnson", 1},
		{"JPMorgan Chase", "jpmorgan-chase", 1},

		// K Brands
		{"Kawasaki", "kawasaki", 1},
		{"KTM", "ktm", 1},
		{"Kellogg's", "kellogg-s", 1},
		{"Kenwood", "kenwood", 1},
		{"Kering", "kering", 1},
		{"KFC", "kfc", 1},
		{"Kia", "kia", 1},
		{"Kiehl's", "kiehl-s", 1},
		{"Kindle", "kindle", 1},
		{"KitKat", "kitkat", 1},
		{"Kodak", "kodak", 1},
		{"Kraft", "kraft", 1},

		// L Brands
		{"L'Oréal", "l-oreal", 1},
		{"Lacoste", "lacoste", 1},
		{"Lamborghini", "lamborghini", 1},
		{"Lancôme", "lancome", 1},
		{"Land Rover", "land-rover", 1},
		{"Lava", "lava", 1},
		{"Lay's", "lay-s", 1},
		{"Lenovo", "lenovo", 1},
		{"Levis", "levis", 1},
		{"Levi's", "levi-s", 1},
		{"Lexus", "lexus", 1},
		{"LG", "lg", 1},
		{"LinkedIn", "linkedin", 1},
		{"Lindt", "lindt", 1},
		{"Lipton", "lipton", 1},
		{"Logitech", "logitech", 1},
		{"Longines", "longines", 1},
		{"Louis Vuitton", "louis-vuitton", 1},
		{"Lululemon", "lululemon", 1},

		// M Brands
		{"MAC", "mac", 1},
		{"Maggi", "maggi", 1},
		{"Mahindra", "mahindra", 1},
		{"Mango", "mango", 1},
		{"Mars", "mars", 1},
		{"Marriott", "marriott", 1},
		{"Maserati", "maserati", 1},
		{"Mastercard", "mastercard", 1},
		{"Mattel", "mattel", 1},
		{"Maui Jim", "maui-jim", 1},
		{"Mazda", "mazda", 1},
		{"McDonald's", "mcdonald-s", 1},
		{"McLaren", "mclaren", 1},
		{"Meizu", "meizu", 1},
		{"Mercedes-Benz", "mercedes-benz", 1},
		{"Meta", "meta", 1},
		{"Michael Kors", "michael-kors", 1},
		{"Michelin", "michelin", 1},
		{"Micromax", "micromax", 1},
		{"Microsoft", "microsoft", 1},
		{"Milka", "milka", 1},
		{"Mini", "mini", 1},
		{"Mitsubishi", "mitsubishi", 1},
		{"Moët & Chandon", "moet-chandon", 1},
		{"Montblanc", "montblanc", 1},
		{"Motorola", "motorola", 1},

		// N Brands
		{"Nescafé", "nescafe", 1},
		{"Nestlé", "nestle", 1},
		{"Netflix", "netflix", 1},
		{"New Balance", "new-balance", 1},
		{"Nike", "nike", 1},
		{"Nikon", "nikon", 1},
		{"Nintendo", "nintendo", 1},
		{"Nissan", "nissan", 1},
		{"Nivea", "nivea", 1},
		{"Nokia", "nokia", 1},
		{"Nongshim", "nongshim", 1},
		{"Nothing", "nothing", 1},
		{"Nutella", "nutella", 1},
		{"Nvidia", "nvidia", 1},

		// O Brands
		{"Olay", "olay", 1},
		{"Olympus", "olympus", 1},
		{"Omega", "omega", 1},
		{"OnePlus", "oneplus", 1},
		{"Oppo", "oppo", 1},
		{"Oracle", "oracle", 1},
		{"Oral-B", "oral-b", 1},
		{"Oreo", "oreo", 1},
		{"Oukitel", "oukitel", 1},

		// P Brands
		{"Panasonic", "panasonic", 1},
		{"Pantene", "pantene", 1},
		{"Patek Philippe", "patek-philippe", 1},
		{"PayPal", "paypal", 1},
		{"Pepsi", "pepsi", 1},
		{"Peugeot", "peugeot", 1},
		{"Pfizer", "pfizer", 1},
		{"Philips", "philips", 1},
		{"Piaggio", "piaggio", 1},
		{"Pizza Hut", "pizza-hut", 1},
		{"Poco", "poco", 1},
		{"Polo", "polo", 1},
		{"Porsche", "porsche", 1},
		{"Prada", "prada", 1},
		{"Procter & Gamble", "procter-gamble", 1},
		{"Puma", "puma", 1},

		// Q Brands
		{"Qualcomm", "qualcomm", 1},

		// R Brands
		{"Raazi", "raazi", 1},
		{"Ralph Lauren", "ralph-lauren", 1},
		{"Razer", "razer", 1},
		{"Ray-Ban", "ray-ban", 1},
		{"Realme", "realme", 1},
		{"Red Bull", "red-bull", 1},
		{"Redmi", "redmi", 1},
		{"Reebok", "reebok", 1},
		{"Remy Martin", "remy-martin", 1},
		{"Renault", "renault", 1},
		{"Ritz-Carlton", "ritz-carlton", 1},
		{"Rolex", "rolex", 1},
		{"Rolls-Royce", "rolls-royce", 1},
		{"Royal Enfield", "royal-enfield", 1},
		{"Road Prince", "road-prince", 1},
		{"Ryanair", "ryanair", 1},

		// S Brands
		{"Saab", "saab", 1},
		{"Saint Laurent", "saint-laurent", 1},
		{"Samsung", "samsung", 1},
		{"Samsun", "samsun", 1},
		{"Sandisk", "sandisk", 1},
		{"Sega", "sega", 1},
		{"Seiko", "seiko", 1},
		{"Sensodyne", "sensodyne", 1},
		{"Sharp", "sharp", 1},
		{"Shell", "shell", 1},
		{"Sheraton", "sheraton", 1},
		{"Siemens", "siemens", 1},
		{"Skechers", "skechers", 1},
		{"Skoda", "skoda", 1},
		{"Slack", "slack", 1},
		{"Snapchat", "snapchat", 1},
		{"Snickers", "snickers", 1},
		{"Sony", "sony", 1},
		{"Spotify", "spotify", 1},
		{"Sprite", "sprite", 1},
		{"Starbucks", "starbucks", 1},
		{"Subaru", "subaru", 1},
		{"Subway", "subway", 1},
		{"Sunglass Hut", "sunglass-hut", 1},
		{"Suzuki", "suzuki", 1},
		{"SYM", "sym", 1},
		{"Swarovski", "swarovski", 1},

		// T Brands
		{"Taco Bell", "taco-bell", 1},
		{"Tag Heuer", "tag-heuer", 1},
		{"Tata", "tata", 1},
		{"TCL", "tcl", 1},
		{"Tecno", "tecno", 1},
		{"Tefal", "tefal", 1},
		{"Tesla", "tesla", 1},
		{"The North Face", "the-north-face", 1},
		{"Thomson", "thomson", 1},
		{"Tiffany & Co.", "tiffany-co", 1},
		{"Timberland", "timberland", 1},
		{"Tissot", "tissot", 1},
		{"T-Mobile", "t-mobile", 1},
		{"Tommy Hilfiger", "tommy-hilfiger", 1},
		{"Tory Burch", "tory-burch", 1},
		{"Toshiba", "toshiba", 1},
		{"Total", "total", 1},
		{"Toyota", "toyota", 1},
		{"Triumph", "triumph", 1},
		{"TVS", "tvs", 1},
		{"Twitter", "twitter", 1},

		// U Brands
		{"Uber", "uber", 1},
		{"Ulefone", "ulefone", 1},
		{"Umidigi", "umidigi", 1},
		{"Under Armour", "under-armour", 1},
		{"Unilever", "unilever", 1},
		{"UPS", "ups", 1},

		// V Brands
		{"Valentino", "valentino", 1},
		{"Vans", "vans", 1},
		{"Vaseline", "vaseline", 1},
		{"Verizon", "verizon", 1},
		{"Versace", "versace", 1},
		{"Victoria's Secret", "victoria-s-secret", 1},
		{"Vichy", "vichy", 1},
		{"Visa", "visa", 1},
		{"Vivo", "vivo", 1},
		{"Vivienne Westwood", "vivienne-westwood", 1},
		{"Vodafone", "vodafone", 1},
		{"Volkswagen", "volkswagen", 1},
		{"Volvo", "volvo", 1},

		// W Brands
		{"Walmart", "walmart", 1},
		{"Wella", "wella", 1},
		{"Western Digital", "western-digital", 1},
		{"Whirlpool", "whirlpool", 1},
		{"WhatsApp", "whatsapp", 1},

		// X Brands
		{"Xbox", "xbox", 1},
		{"Xerox", "xerox", 1},
		{"Xiaomi", "xiaomi", 1},

		// Y Brands
		{"Yahoo", "yahoo", 1},
		{"Yamaha", "yamaha", 1},
		{"YouTube", "youtube", 1},
		{"Yves Saint Laurent", "yves-saint-laurent", 1},

		// Z Brands
		{"Zara", "zara", 1},
		{"Zegna", "zegna", 1},
		{"Zenith", "zenith", 1},
		{"Zippo", "zippo", 1},
		{"Zoom", "zoom", 1},
		{"ZTE", "zte", 1},

		// Bangladeshi Brands
		{"ACI", "aci", 1},
		{"ACI Motors", "aci-motors", 1},
		{"Adoree", "adoree", 1},
		{"Aarong", "aarong", 1},
		{"Ahmed Foods", "ahmed-foods", 1},
		{"Akij", "akij", 1},
		{"Akij Food", "akij-food", 1},
		{"Apex", "apex", 1},
		{"Apex Footwear", "apex-footwear", 1},
		{"Aromatic", "aromatic", 1},
		{"Athlete", "athlete", 1},
		{"Bata Bangladesh", "bata-bangladesh", 1},
		{"Bashundhara", "bashundhara", 1},
		{"Bashundhara Tissue", "bashundhara-tissue", 1},
		{"Bengal", "bengal", 1},
		{"Bengal Meat", "bengal-meat", 1},
		{"BRAC", "brac", 1},
		{"Brother", "brother-bd", 1},
		{"Butterfly", "butterfly", 1},
		{"City Group", "city-group", 1},
		{"Deshbandhu", "deshbandhu", 1},
		{"Destiny", "destiny", 1},
		{"Dhaka Ice Cream", "dhaka-ice-cream", 1},
		{"Emon", "emon", 1},
		{"Fair & Lovely Bangladesh", "fair-lovely-bangladesh", 1},
		{"Fresh", "fresh", 1},
		{"Gadoon", "gadoon", 1},
		{"Golden Harvest", "golden-harvest", 1},
		{"Haque", "haque", 1},
		{"Hatil", "hatil", 1},
		{"Igloo", "igloo", 1},
		{"Jamuna", "jamuna", 1},
		{"Jamuna Electronics", "jamuna-electronics", 1},
		{"Keya", "keya", 1},
		{"Kazi Farms", "kazi-farms", 1},
		{"Lotto", "lotto", 1},
		{"Meena Bazar", "meena-bazar", 1},
		{"Minister", "minister", 1},
		{"Mohammadi", "mohammadi", 1},
		{"Monno", "monno", 1},
		{"Mouchak", "mouchak", 1},
		{"Navana", "navana", 1},
		{"Navana Group", "navana-group", 1},
		{"Nandos", "nandos", 1},
		{"Nasir Group", "nasir-group", 1},
		{"Olympic", "olympic", 1},
		{"Partex", "partex", 1},
		{"Polar", "polar", 1},
		{"Pran", "pran", 1},
		{"Pran-RFL", "pran-rfl", 1},
		{"Pran Frooto", "pran-frooto", 1},
		{"Radhuni", "radhuni", 1},
		{"Rahimafrooz", "rahimafrooz", 1},
		{"RFL", "rfl", 1},
		{"Ruchi", "ruchi", 1},
		{"Runner", "runner", 1},
		{"Rupchanda", "rupchanda", 1},
		{"Rangs", "rangs", 1},
		{"Sajeeb", "sajeeb", 1},
		{"Samsung Bangladesh", "samsung-bangladesh", 1},
		{"Sheetal", "sheetal", 1},
		{"Singer", "singer", 1},
		{"Singer Bangladesh", "singer-bangladesh", 1},
		{"Smart", "smart", 1},
		{"Square", "square", 1},
		{"Square Food", "square-food", 1},
		{"Square Pharma", "square-pharma", 1},
		{"Square Toiletries", "square-toiletries", 1},
		{"Summit", "summit", 1},
		{"Sundarban", "sundarban", 1},
		{"Symphony", "symphony", 1},
		{"Teer", "teer", 1},
		{"Tiger", "tiger", 1},
		{"Transcom", "transcom", 1},
		{"Vision", "vision", 1},
		{"Vision Electronics", "vision-electronics", 1},
		{"Walton", "walton", 1},
		{"Westecs", "westecs", 1},
		{"Yellow", "yellow", 1},
		{"Zamzam", "zamzam", 1},
	}

	for _, brand := range brands {
		brandEntity := &entities.Brand{
			Name:   brand.Name,
			Slug:   brand.Slug,
			Status: brand.Status,
		}

		var brandModel models.BrandModel
		// Check if brand already exists
		if err := db.Where("name = ?", brand.Name).First(&brandModel).Error; err != nil {
			if err == gorm.ErrRecordNotFound {
				// Create new brand
				brandModel.FromEntity(brandEntity)
				if err := db.Create(&brandModel).Error; err != nil {
					return err
				}
			} else {
				return err
			}
		}
	}

	return nil
}
