package seeders

import (
	"gorm.io/gorm"
)

// BrandCategorySeeder handles seeding brand-category relationships
type BrandCategorySeeder struct {
	BaseSeeder
}

// NewBrandCategorySeeder creates a new brand-category seeder
func NewBrandCategorySeeder() *BrandCategorySeeder {
	return &BrandCategorySeeder{
		BaseSeeder: BaseSeeder{name: "Brand Categories"},
	}
}

// Seed implements the Seeder interface
func (bcs *BrandCategorySeeder) Seed(db *gorm.DB) error {
	// Comprehensive brand-category relationships
	brandCategoryMappings := map[string][]string{
		// International Brands - A
		"Abercrombie & Fitch": {"Fashion", "Clothing", "Retail"},
		"Acer":                {"Technology", "Computers", "Electronics", "Laptops"},
		"Adidas":              {"Footwear", "Clothing", "Sports Equipment"},
		"Airbus":              {"Aerospace", "Industrial Equipment"},
		"Alcatel":             {"Technology", "Mobile Phones", "Telecommunications"},
		"Allianz":             {"Financial Services", "Insurance"},
		"Amazon":              {"Retail", "Online Marketplace", "Technology", "Books", "Electronics"},
		"AMD":                 {"Technology", "Computer Hardware", "Semiconductors"},
		"American Express":    {"Financial Services", "Payment Services", "Banking"},
		"Apple":               {"Electronics", "Mobile Phones", "Laptops", "Technology"},
		"Arla":                {"Food & Beverage", "Dairy Products"},
		"Armani":              {"Fashion", "Luxury Goods", "Clothing"},
		"Asus":                {"Technology", "Computers", "Electronics", "Mobile Phones"},
		"Aston Martin":        {"Automotive", "Luxury Cars", "Sports Cars"},
		"Audi":                {"Automotive", "Luxury Cars"},
		"Avon":                {"Beauty Products", "Personal Care", "Cosmetics"},

		// International Brands - B
		"Baidu":          {"Technology", "Search Engine", "Internet Services"},
		"Bajaj":          {"Automotive", "Motorcycles", "Industrial Equipment"},
		"Balenciaga":     {"Fashion", "Luxury Goods", "Accessories"},
		"Barclays":       {"Financial Services", "Banking", "Investment"},
		"Bata":           {"Footwear", "Fashion", "Retail"},
		"Beats":          {"Electronics", "Audio Equipment"},
		"Ben & Jerry's":  {"Food & Beverage", "Ice Cream"},
		"Bentley":        {"Automotive", "Luxury Cars"},
		"Blackberry":     {"Technology", "Mobile Phones", "Software"},
		"Blackview":      {"Technology", "Mobile Phones"},
		"BMW":            {"Automotive", "Luxury Cars", "Motorcycles"},
		"Bosch":          {"Industrial Equipment", "Home Appliances", "Automotive"},
		"Bose":           {"Electronics", "Audio Equipment"},
		"Bottega Veneta": {"Fashion", "Luxury Goods", "Accessories"},
		"Braun":          {"Electronics", "Personal Care", "Home Appliances"},
		"Bridgestone":    {"Automotive", "Tires"},
		"Brother":        {"Electronics", "Printers", "Office Supplies"},
		"Budweiser":      {"Beverages", "Alcoholic Beverages", "Beer"},
		"Bugatti":        {"Automotive", "Luxury Cars", "Sports Cars"},
		"Bulgari":        {"Jewelry", "Luxury Goods"},
		"Burberry":       {"Fashion", "Luxury Goods", "Clothing"},

		// International Brands - C
		"Cadbury":      {"Food & Beverage", "Confectionery", "Sweets"},
		"Cadillac":     {"Automotive", "Luxury Cars"},
		"Calvin Klein": {"Fashion", "Clothing", "Perfumes"},
		"Canon":        {"Electronics", "Cameras", "Photography", "Printers"},
		"Carlsberg":    {"Beverages", "Alcoholic Beverages", "Beer"},
		"Cartier":      {"Jewelry", "Luxury Goods"},
		"Casio":        {"Electronics", "Watches"},
		"CAT":          {"Footwear", "Clothing", "Industrial Equipment"},
		"Chanel":       {"Fashion", "Luxury Goods", "Perfumes", "Beauty Products"},
		"Chevrolet":    {"Automotive", "Cars", "Trucks"},
		"Chivas Regal": {"Beverages", "Alcoholic Beverages"},
		"Cisco":        {"Technology", "Networking", "Telecommunications"},
		"Citizen":      {"Electronics", "Watches"},
		"Clarins":      {"Beauty Products", "Skincare", "Cosmetics"},
		"Clinique":     {"Beauty Products", "Skincare", "Cosmetics"},
		"Coach":        {"Fashion", "Luxury Goods", "Accessories"},
		"Coca-Cola":    {"Beverages", "Soft Drinks"},
		"Colgate":      {"Personal Care", "Oral Care"},
		"Converse":     {"Footwear", "Clothing", "Sports Equipment"},
		"Cooper's":     {"Beverages", "Alcoholic Beverages", "Beer"},
		"Corona":       {"Beverages", "Alcoholic Beverages", "Beer"},
		"Crocs":        {"Footwear", "Casual Wear"},
		"Cubot":        {"Technology", "Mobile Phones"},

		// International Brands - D
		"Daewoo":          {"Automotive", "Electronics", "Industrial Equipment"},
		"Daihatsu":        {"Automotive", "Cars"},
		"Daikin":          {"Home Appliances", "Industrial Equipment"},
		"Danone":          {"Food & Beverage", "Dairy Products", "Nutrition"},
		"Deckard":         {"Technology", "Electronics"},
		"Dell":            {"Technology", "Computers", "Electronics", "Laptops"},
		"DHL":             {"Logistics", "Shipping"},
		"Diesel":          {"Fashion", "Clothing", "Accessories"},
		"Dior":            {"Fashion", "Luxury Goods", "Beauty Products", "Perfumes"},
		"Disney":          {"Entertainment", "Media", "Theme Parks"},
		"Dodge":           {"Automotive", "Cars", "Trucks"},
		"Dolce & Gabbana": {"Fashion", "Luxury Goods", "Perfumes"},
		"Doogee":          {"Technology", "Mobile Phones"},
		"Dove":            {"Personal Care", "Beauty Products"},
		"Dr. Martens":     {"Footwear", "Fashion"},
		"Dropbox":         {"Technology", "Cloud Storage", "Software"},
		"Ducati":          {"Motorcycles", "Automotive"},
		"Dunlop":          {"Automotive", "Tires", "Sports Equipment"},
		"Duracell":        {"Electronics", "Batteries"},

		// International Brands - E
		"eBay":         {"Retail", "Online Marketplace"},
		"Electrolux":   {"Home Appliances", "Kitchen Appliances"},
		"Emirates":     {"Airline", "Travel"},
		"Energizer":    {"Electronics", "Batteries"},
		"Epson":        {"Electronics", "Printers", "Printing"},
		"Ericsson":     {"Technology", "Telecommunications", "Networking"},
		"Estée Lauder": {"Beauty Products", "Cosmetics", "Skincare"},

		// International Brands - F
		"Facebook":  {"Technology", "Social Media", "Internet Services"},
		"Fairphone": {"Technology", "Mobile Phones"},
		"Fanta":     {"Beverages", "Soft Drinks"},
		"FedEx":     {"Logistics", "Shipping"},
		"Fendi":     {"Fashion", "Luxury Goods", "Accessories"},
		"Ferrari":   {"Automotive", "Luxury Cars", "Sports Cars"},
		"Ferrero":   {"Food & Beverage", "Confectionery", "Sweets"},
		"Fiat":      {"Automotive", "Cars"},
		"Fila":      {"Footwear", "Clothing", "Sports Equipment"},
		"Fitbit":    {"Electronics", "Fitness", "Health & Beauty"},
		"Ford":      {"Automotive", "Cars", "Trucks"},
		"Fossil":    {"Watches", "Accessories", "Jewelry"},
		"Fujifilm":  {"Electronics", "Cameras", "Photography"},

		// International Brands - G
		"GAP":            {"Fashion", "Clothing", "Retail"},
		"Garmin":         {"Electronics", "Fitness", "Technology"},
		"Gatorade":       {"Beverages", "Sports Drinks"},
		"GE":             {"Industrial Equipment", "Home Appliances", "Electronics"},
		"General Motors": {"Automotive", "Cars", "Trucks"},
		"Geox":           {"Footwear", "Fashion"},
		"Gillette":       {"Personal Care", "Beauty Products"},
		"Givenchy":       {"Fashion", "Luxury Goods", "Beauty Products"},
		"Glenfiddich":    {"Beverages", "Alcoholic Beverages"},
		"GMC":            {"Automotive", "Trucks"},
		"Godrej":         {"Home Appliances", "Industrial Equipment", "Personal Care"},
		"GoPro":          {"Electronics", "Cameras", "Technology"},
		"Google":         {"Technology", "Search Engine", "Software", "Internet Services"},
		"Goodyear":       {"Automotive", "Tires"},
		"Gucci":          {"Fashion", "Luxury Goods", "Accessories"},
		"Guess":          {"Fashion", "Clothing", "Accessories"},

		// International Brands - H
		"H&M":             {"Fashion", "Clothing", "Retail"},
		"Haier":           {"Home Appliances", "Electronics"},
		"Harley-Davidson": {"Motorcycles", "Automotive"},
		"Havaianas":       {"Footwear", "Flip-Flops"},
		"Heineken":        {"Beverages", "Alcoholic Beverages", "Beer"},
		"Heinz":           {"Food & Beverage", "Groceries"},
		"Hermès":          {"Fashion", "Luxury Goods", "Accessories"},
		"Hershey's":       {"Food & Beverage", "Confectionery", "Sweets"},
		"Hewlett-Packard": {"Technology", "Computers", "Printers", "Electronics"},
		"Hilton":          {"Hotels", "Hospitality", "Travel"},
		"Hitachi":         {"Electronics", "Industrial Equipment", "Home Appliances"},
		"Hisense":         {"Electronics", "Home Appliances"},
		"Honda":           {"Automotive", "Cars", "Motorcycles"},
		"Honor":           {"Technology", "Mobile Phones"},
		"HTC":             {"Technology", "Mobile Phones", "Electronics"},
		"Huawei":          {"Technology", "Mobile Phones", "Telecommunications", "Electronics"},
		"Hugo Boss":       {"Fashion", "Clothing", "Luxury Goods"},
		"Hunter":          {"Footwear", "Outdoor Gear", "Clothing"},
		"Hyundai":         {"Automotive", "Cars"},

		// International Brands - I
		"IBM":     {"Technology", "Software", "Consulting", "Computer Hardware"},
		"IKEA":    {"Furniture", "Home Appliances", "Retail"},
		"Infinix": {"Technology", "Mobile Phones"},
		"Intel":   {"Technology", "Computer Hardware", "Semiconductors"},
		"Itel":    {"Technology", "Mobile Phones"},

		// International Brands - J
		"Jack Daniel's":     {"Beverages", "Alcoholic Beverages"},
		"Jaguar":            {"Automotive", "Luxury Cars"},
		"Jameson":           {"Beverages", "Alcoholic Beverages"},
		"JBL":               {"Electronics", "Audio Equipment"},
		"Jeep":              {"Automotive", "Cars"},
		"JioPhone":          {"Technology", "Mobile Phones"},
		"Johnson & Johnson": {"Healthcare", "Personal Care", "Pharmaceuticals"},
		"JPMorgan Chase":    {"Financial Services", "Banking", "Investment"},

		// International Brands - K
		"Kawasaki":  {"Motorcycles", "Automotive", "Industrial Equipment"},
		"Kellogg's": {"Food & Beverage", "Groceries"},
		"Kenwood":   {"Electronics", "Audio Equipment", "Kitchen Appliances"},
		"Kering":    {"Fashion", "Luxury Goods"},
		"KFC":       {"Fast Food", "Restaurants"},
		"Kia":       {"Automotive", "Cars"},
		"Kiehl's":   {"Beauty Products", "Personal Care", "Skincare"},
		"Kindle":    {"Electronics", "Books", "Technology"},
		"KitKat":    {"Food & Beverage", "Confectionery", "Sweets"},
		"Kodak":     {"Electronics", "Cameras", "Photography"},
		"Kraft":     {"Food & Beverage", "Groceries"},

		// International Brands - L
		"L'Oréal":       {"Beauty Products", "Personal Care", "Cosmetics", "Hair Care"},
		"Lacoste":       {"Fashion", "Clothing", "Sports Equipment"},
		"Lamborghini":   {"Automotive", "Luxury Cars", "Sports Cars"},
		"Lancôme":       {"Beauty Products", "Cosmetics", "Skincare"},
		"Land Rover":    {"Automotive", "Cars"},
		"Lava":          {"Technology", "Mobile Phones"},
		"Lay's":         {"Food & Beverage", "Groceries"},
		"Lenovo":        {"Technology", "Computers", "Electronics", "Mobile Phones", "Laptops"},
		"Levis":         {"Fashion", "Clothing", "Denim"},
		"Levi's":        {"Fashion", "Clothing", "Denim"},
		"Lexus":         {"Automotive", "Luxury Cars"},
		"LG":            {"Electronics", "Home Appliances", "Mobile Phones"},
		"LinkedIn":      {"Technology", "Social Media", "Internet Services"},
		"Lindt":         {"Food & Beverage", "Confectionery", "Sweets"},
		"Lipton":        {"Beverages", "Food & Beverage"},
		"Logitech":      {"Electronics", "Computer Hardware", "Technology"},
		"Longines":      {"Watches", "Luxury Goods", "Jewelry"},
		"Louis Vuitton": {"Fashion", "Luxury Goods", "Accessories"},
		"Lululemon":     {"Clothing", "Sports Equipment", "Fitness"},

		// International Brands - M
		"MAC":            {"Beauty Products", "Cosmetics"},
		"Maggi":          {"Food & Beverage", "Groceries"},
		"Mahindra":       {"Automotive", "Cars", "Industrial Equipment"},
		"Mango":          {"Fashion", "Clothing", "Retail"},
		"Mars":           {"Food & Beverage", "Confectionery", "Sweets"},
		"Marriott":       {"Hotels", "Hospitality", "Travel"},
		"Maserati":       {"Automotive", "Luxury Cars", "Sports Cars"},
		"Mastercard":     {"Financial Services", "Payment Services"},
		"Mattel":         {"Toys", "Entertainment"},
		"Maui Jim":       {"Accessories", "Eyewear"},
		"Mazda":          {"Automotive", "Cars"},
		"McDonald's":     {"Fast Food", "Restaurants"},
		"McLaren":        {"Automotive", "Luxury Cars", "Sports Cars"},
		"Meizu":          {"Technology", "Mobile Phones"},
		"Mercedes-Benz":  {"Automotive", "Luxury Cars"},
		"Meta":           {"Technology", "Social Media", "Internet Services"},
		"Michael Kors":   {"Fashion", "Luxury Goods", "Accessories"},
		"Michelin":       {"Automotive", "Tires"},
		"Micromax":       {"Technology", "Mobile Phones"},
		"Microsoft":      {"Technology", "Software", "Computer Hardware", "Gaming"},
		"Milka":          {"Food & Beverage", "Confectionery", "Sweets"},
		"Mini":           {"Automotive", "Cars"},
		"Mitsubishi":     {"Automotive", "Cars", "Industrial Equipment"},
		"Moët & Chandon": {"Beverages", "Alcoholic Beverages", "Champagne"},
		"Montblanc":      {"Luxury Goods", "Writing Instruments", "Accessories"},
		"Motorola":       {"Technology", "Mobile Phones", "Telecommunications"},

		// International Brands - N
		"Nescafé":     {"Beverages", "Coffee", "Food & Beverage"},
		"Nestlé":      {"Food & Beverage", "Confectionery", "Nutrition", "Groceries"},
		"Netflix":     {"Entertainment", "Media", "Technology"},
		"New Balance": {"Footwear", "Clothing", "Sports Equipment"},
		"Nike":        {"Footwear", "Clothing", "Sports Equipment"},
		"Nikon":       {"Electronics", "Cameras", "Photography"},
		"Nintendo":    {"Gaming", "Entertainment", "Technology"},
		"Nissan":      {"Automotive", "Cars"},
		"Nivea":       {"Personal Care", "Beauty Products", "Skincare"},
		"Nokia":       {"Technology", "Mobile Phones", "Telecommunications"},
		"Nongshim":    {"Food & Beverage", "Groceries"},
		"Nothing":     {"Technology", "Mobile Phones", "Electronics"},
		"Nutella":     {"Food & Beverage", "Confectionery"},
		"Nvidia":      {"Technology", "Computer Hardware", "Semiconductors", "Gaming"},

		// International Brands - O
		"Olay":    {"Beauty Products", "Personal Care", "Skincare"},
		"Olympus": {"Electronics", "Cameras", "Photography", "Healthcare"},
		"Omega":   {"Watches", "Luxury Goods", "Jewelry"},
		"OnePlus": {"Technology", "Mobile Phones"},
		"Oppo":    {"Technology", "Mobile Phones"},
		"Oracle":  {"Technology", "Software", "Consulting"},
		"Oral-B":  {"Personal Care", "Oral Care"},
		"Oreo":    {"Food & Beverage", "Confectionery", "Cookies"},
		"Oukitel": {"Technology", "Mobile Phones"},

		// International Brands - P
		"Panasonic":        {"Electronics", "Home Appliances", "Cameras"},
		"Pantene":          {"Beauty Products", "Hair Care", "Personal Care"},
		"Patek Philippe":   {"Watches", "Luxury Goods", "Jewelry"},
		"PayPal":           {"Financial Services", "Payment Services", "Technology"},
		"Pepsi":            {"Beverages", "Soft Drinks"},
		"Peugeot":          {"Automotive", "Cars"},
		"Pfizer":           {"Healthcare", "Pharmaceuticals"},
		"Philips":          {"Electronics", "Healthcare", "Home Appliances"},
		"Piaggio":          {"Motorcycles", "Automotive"},
		"Pizza Hut":        {"Fast Food", "Restaurants"},
		"Poco":             {"Technology", "Mobile Phones"},
		"Polo":             {"Fashion", "Clothing"},
		"Porsche":          {"Automotive", "Luxury Cars", "Sports Cars"},
		"Prada":            {"Fashion", "Luxury Goods", "Accessories"},
		"Procter & Gamble": {"Personal Care", "Household Goods"},
		"Puma":             {"Footwear", "Clothing", "Sports Equipment"},

		// International Brands - Q
		"Qualcomm": {"Technology", "Semiconductors", "Telecommunications"},

		// International Brands - R
		"Raazi":         {"Technology", "Mobile Phones"},
		"Ralph Lauren":  {"Fashion", "Clothing", "Luxury Goods"},
		"Razer":         {"Electronics", "Gaming", "Computer Hardware"},
		"Ray-Ban":       {"Accessories", "Eyewear"},
		"Realme":        {"Technology", "Mobile Phones"},
		"Red Bull":      {"Beverages", "Energy Drinks", "Sports"},
		"Redmi":         {"Technology", "Mobile Phones"},
		"Reebok":        {"Footwear", "Clothing", "Sports Equipment"},
		"Remy Martin":   {"Beverages", "Alcoholic Beverages", "Cognac"},
		"Renault":       {"Automotive", "Cars"},
		"Ritz-Carlton":  {"Hotels", "Hospitality", "Luxury Services"},
		"Rolex":         {"Watches", "Luxury Goods", "Jewelry"},
		"Rolls-Royce":   {"Automotive", "Luxury Cars", "Aerospace"},
		"Royal Enfield": {"Motorcycles", "Automotive"},
		"Ryanair":       {"Airline", "Travel"},

		// International Brands - S
		"Saab":          {"Automotive", "Cars", "Aerospace"},
		"Saint Laurent": {"Fashion", "Luxury Goods", "Accessories"},
		"Samsung":       {"Electronics", "Mobile Phones", "Home Appliances", "Technology"},
		"Samsun":        {"Food & Beverage", "Groceries"},
		"Sandisk":       {"Electronics", "Technology", "Computer Hardware"},
		"Sega":          {"Gaming", "Entertainment"},
		"Seiko":         {"Watches", "Electronics"},
		"Sensodyne":     {"Personal Care", "Oral Care"},
		"Sharp":         {"Electronics", "Home Appliances"},
		"Shell":         {"Automotive", "Industrial Equipment"},
		"Sheraton":      {"Hotels", "Hospitality", "Travel"},
		"Siemens":       {"Industrial Equipment", "Electronics", "Healthcare"},
		"Skechers":      {"Footwear", "Clothing"},
		"Skoda":         {"Automotive", "Cars"},
		"Slack":         {"Technology", "Software", "Internet Services"},
		"Snapchat":      {"Technology", "Social Media", "Internet Services"},
		"Snickers":      {"Food & Beverage", "Confectionery", "Sweets"},
		"Sony":          {"Electronics", "Entertainment", "Gaming", "Cameras"},
		"Spotify":       {"Entertainment", "Technology", "Internet Services"},
		"Sprite":        {"Beverages", "Soft Drinks"},
		"Starbucks":     {"Coffee", "Restaurants", "Beverages"},
		"Subaru":        {"Automotive", "Cars"},
		"Subway":        {"Fast Food", "Restaurants"},
		"Sunglass Hut":  {"Accessories", "Eyewear", "Retail"},
		"Suzuki":        {"Automotive", "Cars", "Motorcycles"},
		"Swarovski":     {"Jewelry", "Luxury Goods", "Crystal"},

		// International Brands - T
		"Taco Bell":      {"Fast Food", "Restaurants"},
		"Tag Heuer":      {"Watches", "Luxury Goods", "Jewelry"},
		"Tata":           {"Automotive", "Cars", "Industrial Equipment", "Conglomerate"},
		"TCL":            {"Electronics", "Home Appliances"},
		"Tecno":          {"Technology", "Mobile Phones"},
		"Tefal":          {"Kitchen Appliances", "Home Appliances"},
		"Tesla":          {"Automotive", "Electric Vehicles", "Technology"},
		"The North Face": {"Clothing", "Sports Equipment", "Outdoor Gear"},
		"Thomson":        {"Electronics", "Home Appliances"},
		"Tiffany & Co.":  {"Jewelry", "Luxury Goods", "Accessories"},
		"Timberland":     {"Footwear", "Clothing", "Outdoor Gear"},
		"Tissot":         {"Watches", "Luxury Goods"},
		"T-Mobile":       {"Telecommunications", "Mobile Services"},
		"Tommy Hilfiger": {"Fashion", "Clothing", "Accessories"},
		"Tory Burch":     {"Fashion", "Luxury Goods", "Accessories"},
		"Toshiba":        {"Electronics", "Home Appliances", "Industrial Equipment"},
		"Total":          {"Automotive", "Industrial Equipment"},
		"Toyota":         {"Automotive", "Cars", "Hybrid Vehicles"},
		"Triumph":        {"Motorcycles", "Automotive"},
		"TVS":            {"Motorcycles", "Automotive"},
		"Twitter":        {"Technology", "Social Media", "Internet Services"},

		// International Brands - U
		"Uber":         {"Technology", "Travel", "Internet Services"},
		"Ulefone":      {"Technology", "Mobile Phones"},
		"Umidigi":      {"Technology", "Mobile Phones"},
		"Under Armour": {"Footwear", "Clothing", "Sports Equipment"},
		"Unilever":     {"Personal Care", "Food & Beverage", "Household Goods"},
		"UPS":          {"Logistics", "Shipping"},

		// International Brands - V
		"Valentino":         {"Fashion", "Luxury Goods", "Accessories"},
		"Vans":              {"Footwear", "Clothing", "Skateboarding"},
		"Vaseline":          {"Personal Care", "Beauty Products"},
		"Verizon":           {"Telecommunications", "Mobile Services"},
		"Versace":           {"Fashion", "Luxury Goods", "Accessories"},
		"Victoria's Secret": {"Fashion", "Clothing", "Beauty Products"},
		"Vichy":             {"Beauty Products", "Personal Care", "Skincare"},
		"Visa":              {"Financial Services", "Payment Services"},
		"Vivo":              {"Technology", "Mobile Phones"},
		"Vivienne Westwood": {"Fashion", "Luxury Goods", "Accessories"},
		"Vodafone":          {"Telecommunications", "Mobile Services"},
		"Volkswagen":        {"Automotive", "Cars"},
		"Volvo":             {"Automotive", "Cars", "Trucks"},

		// International Brands - W
		"Walmart":         {"Retail", "Groceries", "Online Marketplace"},
		"Wella":           {"Beauty Products", "Hair Care"},
		"Western Digital": {"Technology", "Computer Hardware", "Electronics"},
		"Whirlpool":       {"Home Appliances", "Kitchen Appliances"},
		"WhatsApp":        {"Technology", "Social Media", "Internet Services"},

		// International Brands - X, Y, Z
		"Xbox":               {"Gaming", "Entertainment", "Technology"},
		"Xerox":              {"Electronics", "Printers", "Office Supplies"},
		"Xiaomi":             {"Technology", "Mobile Phones", "Electronics", "Home Appliances"},
		"Yahoo":              {"Technology", "Internet Services"},
		"Yamaha":             {"Motorcycles", "Musical Instruments", "Electronics"},
		"YouTube":            {"Entertainment", "Media", "Technology", "Internet Services"},
		"Yves Saint Laurent": {"Fashion", "Luxury Goods", "Beauty Products"},
		"Zara":               {"Fashion", "Clothing", "Retail"},
		"Zegna":              {"Fashion", "Luxury Goods", "Clothing"},
		"Zenith":             {"Watches", "Luxury Goods", "Electronics"},
		"Zippo":              {"Accessories", "Lifestyle"},
		"Zoom":               {"Technology", "Software", "Internet Services"},
		"ZTE":                {"Technology", "Mobile Phones", "Telecommunications"},

		// Bangladeshi Brands
		"ACI":                      {"Conglomerate", "Multiple Industries", "Healthcare", "Food & Beverage", "Personal Care"},
		"ACI Motors":               {"Automotive", "Motorcycles"},
		"Adoree":                   {"Fashion", "Clothing", "Retail"},
		"Aarong":                   {"Fashion", "Clothing", "Retail", "Handicrafts"},
		"Ahmed Foods":              {"Food & Beverage", "Groceries"},
		"Akij":                     {"Conglomerate", "Multiple Industries", "Food & Beverage", "Industrial Equipment"},
		"Akij Food":                {"Food & Beverage", "Groceries", "Beverages"},
		"Apex":                     {"Footwear", "Fashion"},
		"Apex Footwear":            {"Footwear", "Fashion", "Retail"},
		"Aromatic":                 {"Food & Beverage", "Groceries"},
		"Athlete":                  {"Footwear", "Sports Equipment"},
		"Bata Bangladesh":          {"Footwear", "Fashion", "Retail"},
		"Bashundhara":              {"Conglomerate", "Multiple Industries", "Packaging", "Retail"},
		"Bashundhara Tissue":       {"Personal Care", "Household Goods"},
		"Bengal":                   {"Food & Beverage", "Groceries"},
		"Bengal Meat":              {"Food & Beverage", "Groceries"},
		"BRAC":                     {"Financial Services", "Healthcare", "Education"},
		"Butterfly":                {"Home Appliances", "Kitchen Appliances", "Kitchenware"},
		"City Group":               {"Conglomerate", "Multiple Industries", "Retail"},
		"Deshbandhu":               {"Food & Beverage", "Groceries"},
		"Destiny":                  {"Conglomerate", "Multiple Industries", "Retail"},
		"Dhaka Ice Cream":          {"Food & Beverage", "Ice Cream"},
		"Emon":                     {"Fashion", "Clothing"},
		"Fair & Lovely Bangladesh": {"Beauty Products", "Personal Care", "Skincare"},
		"Fresh":                    {"Food & Beverage", "Dairy Products", "Groceries"},
		"Gadoon":                   {"Food & Beverage", "Bakery", "Confectionery"},
		"Golden Harvest":           {"Food & Beverage", "Ice Cream"},
		"Haque":                    {"Food & Beverage", "Groceries"},
		"Hatil":                    {"Furniture", "Home Appliances", "Retail"},
		"Igloo":                    {"Food & Beverage", "Ice Cream"},
		"Jamuna":                   {"Conglomerate", "Multiple Industries"},
		"Jamuna Electronics":       {"Electronics", "Home Appliances", "Retail"},
		"Keya":                     {"Food & Beverage", "Groceries"},
		"Kazi Farms":               {"Food & Beverage", "Groceries"},
		"Lotto":                    {"Footwear", "Sports Equipment"},
		"Meena Bazar":              {"Retail", "Groceries"},
		"Minister":                 {"Electronics", "Home Appliances"},
		"Mohammadi":                {"Food & Beverage", "Groceries"},
		"Monno":                    {"Conglomerate", "Industrial Equipment", "Food & Beverage"},
		"Mouchak":                  {"Food & Beverage", "Sweets", "Confectionery"},
		"Navana":                   {"Conglomerate", "Multiple Industries", "Automotive"},
		"Navana Group":             {"Conglomerate", "Multiple Industries", "Automotive", "Retail"},
		"Nandos":                   {"Fast Food", "Restaurants"},
		"Nasir Group":              {"Conglomerate", "Multiple Industries", "Industrial Equipment"},
		"Olympic":                  {"Electronics", "Home Appliances", "Retail"},
		"Partex":                   {"Conglomerate", "Multiple Industries", "Industrial Equipment"},
		"Polar":                    {"Food & Beverage", "Ice Cream"},
		"Pran":                     {"Food & Beverage", "Groceries", "Beverages"},
		"Pran-RFL":                 {"Conglomerate", "Multiple Industries", "Food & Beverage", "Household Goods"},
		"Pran Frooto":              {"Beverages", "Food & Beverage"},
		"Radhuni":                  {"Food & Beverage", "Groceries"},
		"Rahimafrooz":              {"Conglomerate", "Electronics", "Automotive", "Industrial Equipment"},
		"RFL":                      {"Household Goods", "Home Appliances", "Kitchenware"},
		"Ruchi":                    {"Food & Beverage", "Groceries"},
		"Runner":                   {"Automotive", "Motorcycles"},
		"Rupchanda":                {"Food & Beverage", "Groceries"},
		"Rangs":                    {"Electronics", "Home Appliances", "Retail"},
		"Sajeeb":                   {"Food & Beverage", "Groceries"},
		"Samsung Bangladesh":       {"Electronics", "Mobile Phones", "Home Appliances"},
		"Sheetal":                  {"Beverages", "Food & Beverage"},
		"Singer":                   {"Electronics", "Home Appliances", "Retail"},
		"Singer Bangladesh":        {"Electronics", "Home Appliances", "Retail"},
		"Smart":                    {"Technology", "Mobile Phones"},
		"Square":                   {"Conglomerate", "Multiple Industries", "Healthcare", "Pharmaceuticals"},
		"Square Food":              {"Food & Beverage", "Groceries"},
		"Square Pharma":            {"Healthcare", "Pharmaceuticals"},
		"Square Toiletries":        {"Personal Care", "Beauty Products", "Household Goods"},
		"Summit":                   {"Conglomerate", "Industrial Equipment"},
		"Sundarban":                {"Food & Beverage", "Groceries"},
		"Symphony":                 {"Electronics", "Mobile Phones"},
		"Teer":                     {"Food & Beverage", "Groceries"},
		"Tiger":                    {"Food & Beverage", "Beverages"},
		"Transcom":                 {"Conglomerate", "Multiple Industries", "Electronics", "Retail"},
		"Vision":                   {"Electronics", "Home Appliances"},
		"Vision Electronics":       {"Electronics", "Home Appliances", "Retail"},
		"Walton":                   {"Electronics", "Home Appliances", "Mobile Phones", "Motorcycles", "Refrigerators"},
		"Westecs":                  {"Industrial Equipment", "Technology"},
		"Yellow":                   {"Technology", "Mobile Phones"},
		"Zamzam":                   {"Beverages", "Food & Beverage"},
	}

	for brandName, categoryNames := range brandCategoryMappings {
		// Get the brand
		brand, err := CreateOrFindBrand(db, brandName, GenerateSlug(brandName))
		if err != nil {
			return err
		}

		for _, categoryName := range categoryNames {
			// Get the category
			category, err := CreateOrFindCategory(db, categoryName, GenerateSlug(categoryName))
			if err != nil {
				return err
			}

			// Create the brand-category relationship
			if err := CreateBrandCategoryRelation(db, brand.ID, category.ID); err != nil {
				return err
			}
		}
	}

	return nil
}
