package seeders

// DefaultMotorcycleSpecs returns a comprehensive set of motorcycle specification keys
// with safe default values. Seeders can call this and override model-specific values.
func DefaultMotorcycleSpecs() map[string]string {
	return map[string]string{
		"ABS (Anti-lock Braking System)": "",
		"CC (Cubic Capacity)":            "",
		"Clutch Type":                    "",
		"Cooling System":                 "",
		"Displacement":                   "",
		"Drive Type":                     "",
		"Engine Type":                    "",
		"Fuel Capacity":                  "",
		"Fuel Tank Capacity":             "",
		"Fuel Type":                      "",
		"Gearbox":                        "",
		"Ground Clearance":               "",
		"Headlight Type":                 "",
		"Horsepower":                     "",
		"Ignition Type":                  "",
		"Kerb Weight":                    "",
		"Length":                         "",
		"Max Power":                      "",
		"Max Torque":                     "",
		"Mileage":                        "",
		"Number of Gears":                "",
		"Number of Seats":                "",
		"Seating Capacity":               "",
		"Starting System":                "",
		"Suspension Type":                "",
		"Top Speed":                      "",
		"Torque":                         "",
		"Transmission":                   "",
		"Tyre Size":                      "",
		"Tyre Type":                      "",
		"Valve Configuration":            "",
		"Wheelbase":                      "",
		"Width":                          "",
		"Brake Type":                     "",
		"Front Brake Type":               "",
		"Rear Brake Type":                "",
		"Rim Type":                       "",
		"Rim Size":                       "",
		"Seat Height":                    "",
		"Battery Capacity":               "",
		"Fuel System":                    "",
		"Emission Standard":              "",
		"Compression Ratio":              "",
		"Instrument Cluster":             "",
		"DRL (Daytime Running Light)":    "",
		"Spark Plug Type":                "",
		"Electrical System":              "",
	}
}
