package seeders

import (
	"kossti/internal/infrastructure/database/models"
	"log"

	"gorm.io/gorm"
)

// MGZSSeeder seeds specifications for MG ZS
type MGZSSeeder struct {
	BaseSeeder
}

// NewMGZSSeeder creates a new MG ZS seeder
func NewMGZSSeeder() *MGZSSeeder {
	return &MGZSSeeder{
		BaseSeeder: BaseSeeder{name: "MG ZS Specifications"},
	}
}

func (mzs *MGZSSeeder) getBanglaTranslations() map[string]string {
	return map[string]string{
		"1.5L":                          "১.৫ লিটার",
		"Subcompact SUV":                "সাবকমপ্যাক্ট এসইউভি",
		"2020":                          "২০২০",
		"SUV":                           "এসইউভি",
		"Arctic White":                  "আর্টিক হোয়াইট",
		"Inline":                        "ইনলাইন",
		"1498":                          "১৪৯৮ সিসি",
		"4":                             "৪ (সিলিন্ডার)",
		"105 hp":                        "১০৫ হর্স পাওয়ার",
		"105 hp @ 6000 rpm":             "৬০০০ আরপিএম এ ১০৫ হর্স পাওয়ার",
		"150 Nm @ 4500 rpm":             "৪৫০০ আরপিএম এ ১৫০ এনএম",
		"Petrol":                        "পেট্রোল",
		"Naturally Aspirated":           "ন্যাচারালি অ্যাসপিরেটেড",
		"10.9 seconds":                  "১০.৯ সেকেন্ড",
		"170 km/h":                      "১৭০ কিমি/ঘণ্টা",
		"18 km/L":                       "১৮ কিমি/লিটার",
		"15 km/L":                       "১৫ কিমি/লিটার",
		"17 km/L":                       "১৭ কিমি/লিটার",
		"Manual (Transmission)":         "ম্যানুয়াল (ট্রান্সমিশন)",
		"5-Speed Manual":                "৫-স্পিড ম্যানুয়াল",
		"Front-Wheel Drive":             "ফ্রন্ট-হুইল ড্রাইভ",
		"Single Plate Dry Clutch":       "সিঙ্গেল প্লেট ড্রাই ক্লাচ",
		"4314 mm":                       "৪৩১৪ মিমি",
		"1809 mm":                       "১৮০৯ মিমি",
		"1636 mm":                       "১৬৩৬ মিমি",
		"2585 mm":                       "২৫৮৫ মিমি",
		"5":                             "৫ (সিট)",
		"5 Doors":                       "৫ ডোর",
		"4 Doors":                       "৪ ডোর",
		"1 Door":                        "১ ডোর",
		"5 Seats":                       "৫ সিট",
		"Black":                         "ব্ল্যাক",
		"Gray":                          "গ্রে",
		"White":                         "হোয়াইট",
		"Silver":                        "সিলভার",
		"Blue":                          "ব্লু",
		"Red":                           "রেড",
		"LED":                           "এলইডি",
		"Halogen":                       "হ্যালোজেন",
		"LED Headlights":                "এলইডি হেডলাইট",
		"Halogen Headlights":            "হ্যালোজেন হেডলাইট",
		"LED Daytime Running Lights":    "এলইডি ডে টাইম রানিং লাইট",
		"Roof Rails":                    "রুফ রেল",
		"No Roof Rails":                 "রুফ রেল নেই",
		"Steel Wheels":                  "স্টিল হুইল",
		"Alloy Wheels":                  "অ্যালয় হুইল",
		"16-inch Alloy Wheels":          "১৬-ইঞ্চি অ্যালয় হুইল",
		"17-inch Alloy Wheels":          "১৭-ইঞ্চি অ্যালয় হুইল",
		"18-inch Alloy Wheels":          "১৮-ইঞ্চি অ্যালয় হুইল",
		"195/60 R16":                    "১৯৫/৬০ আর১৬",
		"205/50 R17":                    "২০৫/৫০ আর১৭",
		"215/45 R18":                    "২১৫/৪৫ আর১৮",
		"Manual Adjustment":             "ম্যানুয়াল অ্যাডজাস্টমেন্ট",
		"Electric Adjustment":           "ইলেকট্রিক অ্যাডজাস্টমেন্ট",
		"Height Adjustable":             "হাইট অ্যাডজাস্টেবল",
		"6-way Manual":                  "৬-ওয়ে ম্যানুয়াল",
		"8-way Electric":                "৮-ওয়ে ইলেকট্রিক",
		"Fabric":                        "ফ্যাব্রিক",
		"Leather":                       "লেদার",
		"Fabric Seats":                  "ফ্যাব্রিক সিট",
		"Leather Seats":                 "লেদার সিট",
		"60:40 Split":                   "৬০:৪০ স্প্লিট",
		"Folding Rear Seats":            "ফোল্ডিং রিয়ার সিট",
		"Manual AC":                     "ম্যানুয়াল এসি",
		"Auto AC":                       "অটো এসি",
		"Single Zone":                   "সিঙ্গেল জোন",
		"Dual Zone":                     "ডুয়াল জোন",
		"Rear AC Vents":                 "রিয়ার এসি ভেন্ট",
		"7-inch Touchscreen":            "৭-ইঞ্চি টাচস্ক্রিন",
		"8-inch Touchscreen":            "৮-ইঞ্চি টাচস্ক্রিন",
		"9-inch Touchscreen":            "৯-ইঞ্চি টাচস্ক্রিন",
		"10-inch Touchscreen":           "১০-ইঞ্চি টাচস্ক্রিন",
		"Android Auto":                  "অ্যান্ড্রয়েড অটো",
		"Apple CarPlay":                 "অ্যাপল কারপ্লে",
		"Bluetooth":                     "ব্লুটুথ",
		"USB":                           "ইউএসবি",
		"AUX":                           "অক্সিলারি",
		"4 Speakers":                    "৪ স্পিকার",
		"6 Speakers":                    "৬ স্পিকার",
		"8 Speakers":                    "৮ স্পিকার",
		"ABS":                           "এবিএস",
		"EBD":                           "ইবিডি",
		"Brake Assist":                  "ব্রেক অ্যাসিস্ট",
		"ESP":                           "ইএসপি",
		"Traction Control":              "ট্র্যাকশন কন্ট্রোল",
		"Hill Hold Control":             "হিল হোল্ড কন্ট্রোল",
		"Front Airbags":                 "ফ্রন্ট এয়ারব্যাগ",
		"Side Airbags":                  "সাইড এয়ারব্যাগ",
		"Curtain Airbags":               "কার্টেন এয়ারব্যাগ",
		"Rear Parking Sensors":          "রিয়ার পার্কিং সেন্সর",
		"Rear Parking Camera":           "রিয়ার পার্কিং ক্যামেরা",
		"360-degree Camera":             "৩৬০-ডিগ্রি ক্যামেরা",
		"ISOFIX":                        "আইএসওফিক্স",
		"Child Safety Locks":            "চাইল্ড সেফটি লক",
		"Speed Sensing Door Locks":      "স্পিড সেন্সিং ডোর লক",
		"Central Locking":               "সেন্ট্রাল লকিং",
		"Keyless Entry":                 "কীলেস এন্ট্রি",
		"Push Button Start":             "পুশ বাটন স্টার্ট",
		"Engine Immobilizer":            "ইঞ্জিন ইমোবিলাইজার",
		"Anti-theft Alarm":              "অ্যান্টি-থেফট অ্যালার্ম",
		"Tyre Pressure Monitoring":      "টায়ার প্রেশার মনিটরিং",
		"Follow-me-home Headlamps":      "ফলো-মি-হোম হেডল্যাম্প",
		"Rain Sensing Wipers":           "রেইন সেন্সিং ওয়াইপার",
		"Auto Headlamps":                "অটো হেডল্যাম্প",
		"Sunroof":                       "সানরুফ",
		"Panoramic Sunroof":             "প্যানোরামিক সানরুফ",
		"Roof Rails":                    "রুফ রেল",
		"Chrome Accents":                "ক্রোম অ্যাকসেন্ট",
		"Body Colored Bumpers":          "বডি কালার্ড বাম্পার",
		"Rear Spoiler":                  "রিয়ার স্পয়লার",
		"Shark Fin Antenna":             "শার্ক ফিন অ্যান্টেনা",
		"LED Tail Lights":               "এলইডি টেইল লাইট",
		"Fog Lights":                    "ফগ লাইট",
		"LED Fog Lights":                "এলইডি ফগ লাইট",
		"Cornering Lights":              "কর্নারিং লাইট",
		"Projector Headlamps":           "প্রজেক্টর হেডল্যাম্প",
		"DRLs":                          "ডিআরএল",
		"LED DRLs":                      "এলইডি ডিআরএল",
		"Digital Instrument Cluster":    "ডিজিটাল ইন্সট্রুমেন্ট ক্লাস্টার",
		"Analog Instrument Cluster":     "অ্যানালগ ইন্সট্রুমেন্ট ক্লাস্টার",
		"Trip Computer":                 "ট্রিপ কম্পিউটার",
		"Tachometer":                    "ট্যাকোমিটার",
		"Gear Shift Indicator":          "গিয়ার শিফ্ট ইন্ডিকেটর",
		"Door Ajar Warning":             "ডোর অজার ওয়ার্নিং",
		"Low Fuel Warning":              "লো ফুয়েল ওয়ার্নিং",
		"12V Power Outlet":              "১২ভি পাওয়ার আউটলেট",
		"Cigarette Lighter":             "সিগারেট লাইটার",
		"Boot Lamp":                     "বুট ল্যাম্প",
		"Vanity Mirrors":                "ভ্যানিটি মিরর",
		"Adjustable Steering":           "অ্যাডজাস্টেবল স্টিয়ারিং",
		"Tilt Steering":                 "টিল্ট স্টিয়ারিং",
		"Telescopic Steering":           "টেলিস্কোপিক স্টিয়ারিং",
		"Height Adjustable Steering":    "হাইট অ্যাডজাস্টেবল স্টিয়ারিং",
		"Leather Steering Wheel":        "লেদার স্টিয়ারিং হুইল",
		"Multi-function Steering":       "মাল্টি-ফাংশন স্টিয়ারিং",
		"Audio Controls":                "অডিও কন্ট্রোল",
		"Voice Commands":                "ভয়েস কমান্ড",
		"Cruise Control":                "ক্রুজ কন্ট্রোল",
		"Wireless Charger":              "ওয়্যারলেস চার্জার",
		"Ambient Lighting":              "অ্যাম্বিয়েন্ট লাইটিং",
		"Footwell Lighting":             "ফুটওয়েল লাইটিং",
		"Reading Lamps":                 "রিডিং ল্যাম্প",
		"Glove Box Lamp":                "গ্লোভ বক্স ল্যাম্প",
		"Trunk Lamp":                    "ট্রাঙ্ক ল্যাম্প",
		"Welcome Function":              "ওয়েলকাম ফাংশন",
		"Auto Dimming IRVM":             "অটো ডিমিং আইআরভিএম",
		"ORVMs with Turn Indicators":    "ওআরভিএম উইথ টার্ন ইন্ডিকেটর",
		"Power Windows":                 "পাওয়ার উইন্ডো",
		"One Touch Up/Down":             "ওয়ান টাচ আপ/ডাউন",
		"Anti-pinch":                    "অ্যান্টি-পিঞ্চ",
		"Boot Release":                  "বুট রিলিজ",
		"Remote Boot Release":           "রিমোট বুট রিলিজ",
		"Rear Defogger":                 "রিয়ার ডিফগার",
		"Rear Wiper":                    "রিয়ার ওয়াইপার",
		"Intermittent Rear Wiper":       "ইন্টারমিটেন্ট রিয়ার ওয়াইপার",
		"Heated ORVMs":                  "হিটেড ওআরভিএম",
		"Electrically Adjustable ORVMs": "ইলেকট্রিক্যালি অ্যাডজাস্টেবল ওআরভিএম",
		"Power Folding ORVMs":           "পাওয়ার ফোল্ডিং ওআরভিএম",
		"Boot Space":                    "বুট স্পেস",
		"378 L":                         "৩৭৮ লিটার",
		"1109 L":                        "১১০৯ লিটার",
		"Fuel Tank":                     "ফুয়েল ট্যাঙ্ক",
		"48 L":                          "৪৮ লিটার",
		"Ground Clearance":              "গ্রাউন্ড ক্লিয়ারেন্স",
		"177 mm":                        "১৭৭ মিমি",
		"Kerb Weight":                   "কার্ব ওয়েট",
		"1195 kg":                       "১১৯৫ কেজি",
		"Gross Weight":                  "গ্রস ওয়েট",
		"1695 kg":                       "১৬৯৫ কেজি",
		"Turning Radius":                "টার্নিং রেডিয়াস",
		"5.6 m":                         "৫.৬ মিটার",
		"Top Speed":                     "টপ স্পিড",
		"170 km/h":                      "১৭০ কিমি/ঘণ্টা",
		"Acceleration 0-100 km/h":       "০-১০০ কিমি/ঘণ্টা অ্যাকসেলারেশন",
		"10.9 seconds":                  "১০.৯ সেকেন্ড",
		"Engine Type":                   "ইঞ্জিন টাইপ",
		"1.5L Naturally Aspirated":      "১.৫লি ন্যাচারালি অ্যাসপিরেটেড",
		"Displacement":                  "ডিসপ্লেসমেন্ট",
		"1498 cc":                       "১৪৯৮ সিসি",
		"Max Power":                     "ম্যাক্স পাওয়ার",
		"105 hp @ 6000 rpm":             "১০৫ হর্স পাওয়ার @ ৬০০০ আরপিএম",
		"Max Torque":                    "ম্যাক্স টর্ক",
		"150 Nm @ 4500 rpm":             "১৫০ এনএম @ ৪৫০০ আরপিএম",
		"No. of Cylinders":              "সিলিন্ডারের সংখ্যা",
		"4":                             "৪",
		"Valves per Cylinder":           "প্রতি সিলিন্ডার ভালভ",
		"4":                             "৪",
		"Fuel Supply System":            "ফুয়েল সাপ্লাই সিস্টেম",
		"MPFI":                          "এমপিএফআই",
		"Bore x Stroke":                 "বোর x স্ট্রোক",
		"74.0 x 86.6 mm":                "৭৪.০ x ৮৬.৬ মিমি",
		"Compression Ratio":             "কম্প্রেশন রেশিও",
		"10.5:1":                        "১০.৫:১",
		"Turbo Charger":                 "টার্বো চার্জার",
		"No":                            "না",
		"Super Charger":                 "সুপার চার্জার",
		"No":                            "না",
		"Transmission Type":             "ট্রান্সমিশন টাইপ",
		"Manual":                        "ম্যানুয়াল",
		"Gear Box":                      "গিয়ার বক্স",
		"5-Speed":                       "৫-স্পিড",
		"Drive Type":                    "ড্রাইভ টাইপ",
		"FWD":                           "এফডব্লিউডি",
		"Clutch Type":                   "ক্লাচ টাইপ",
		"Single Plate Dry Clutch":       "সিঙ্গেল প্লেট ড্রাই ক্লাচ",
		"Mileage (ARAI)":                "মাইলেজ (এআরএআই)",
		"18 km/L":                       "১৮ কিমি/লিটার",
		"Mileage (City)":                "মাইলেজ (সিটি)",
		"15 km/L":                       "১৫ কিমি/লিটার",
		"Mileage (Highway)":             "মাইলেজ (হাইওয়ে)",
		"20 km/L":                       "২০ কিমি/লিটার",
		"Emission Norm Compliance":      "ইমিশন নর্ম কমপ্লায়েন্স",
		"BS VI":                         "বিএস ভি",
		"Length":                        "দৈর্ঘ্য",
		"4314 mm":                       "৪৩১৪ মিমি",
		"Width":                         "প্রস্থ",
		"1809 mm":                       "১৮০৯ মিমি",
		"Height":                        "উচ্চতা",
		"1636 mm":                       "১৬৩৬ মিমি",
		"Wheelbase":                     "হুইলবেস",
		"2585 mm":                       "২৫৮৫ মিমি",
		"Front Tread":                   "ফ্রন্ট ট্রেড",
		"1521 mm":                       "১৫২১ মিমি",
		"Rear Tread":                    "রিয়ার ট্রেড",
		"1524 mm":                       "১৫২৪ মিমি",
		"Seating Capacity":              "সিটিং ক্যাপাসিটি",
		"5":                             "৫",
		"Door Count":                    "ডোর কাউন্ট",
		"5":                             "৫",
		"Boot Space":                    "বুট স্পেস",
		"378 L":                         "৩৭৮ লিটার",
		"Fuel Tank Capacity":            "ফুয়েল ট্যাঙ্ক ক্যাপাসিটি",
		"48 L":                          "৪৮ লিটার",
		"Ground Clearance Unladen":      "গ্রাউন্ড ক্লিয়ারেন্স আনলোডেড",
		"177 mm":                        "১৭৭ মিমি",
		"Kerb Weight":                   "কার্ব ওয়েট",
		"1195 kg":                       "১১৯৫ কেজি",
		"Gross Weight":                  "গ্রস ওয়েট",
		"1695 kg":                       "১৬৯৫ কেজি",
		"Turning Radius":                "টার্নিং রেডিয়াস",
		"5.6 m":                         "৫.৬ মিটার",
		"Front Suspension":              "ফ্রন্ট সাসপেনশন",
		"MacPherson Strut":              "ম্যাকফারসন স্ট্রাট",
		"Rear Suspension":               "রিয়ার সাসপেনশন",
		"Torsion Beam":                  "টর্শন বিম",
		"Front Brake Type":              "ফ্রন্ট ব্রেক টাইপ",
		"Disc":                          "ডিস্ক",
		"Rear Brake Type":               "রিয়ার ব্রেক টাইপ",
		"Drum":                          "ড্রাম",
		"Tyre Size":                     "টায়ার সাইজ",
		"195/60 R16":                    "১৯৫/৬০ আর১৬",
		"Wheel Size":                    "হুইল সাইজ",
		"16 inches":                     "১৬ ইঞ্চি",
		"Spare Tyre Size":               "স্পেয়ার টায়ার সাইজ",
		"195/60 R16":                    "১৯৫/৬০ আর১৬",
	}
}

func (mzs *MGZSSeeder) Seed(db *gorm.DB) error {
	// First, find or create the product
	var product models.ProductModel
	if err := db.Where("name = ?", "MG ZS").First(&product).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			product = models.ProductModel{
				Name:        "MG ZS",
				Brand:       "MG",
				Category:    "SUV",
				Subcategory: "Subcompact SUV",
				Status:      1,
			}
			if err := db.Create(&product).Error; err != nil {
				return err
			}
			log.Printf("Created product: %s", product.Name)
		} else {
			return err
		}
	}

	// Get all specification keys
	var specKeys []models.SpecificationKeyModel
	if err := db.Find(&specKeys).Error; err != nil {
		return err
	}

	// Create a map for quick lookup
	specKeyMap := make(map[string]uint)
	for _, key := range specKeys {
		specKeyMap[key.Key] = key.ID
	}

	// Define specifications
	specifications := map[string]string{
		"engine_type":                 "1.5L Naturally Aspirated",
		"engine_displacement":         "1498 cc",
		"engine_cylinders":            "4",
		"engine_valves_per_cylinder":  "4",
		"engine_configuration":        "Inline",
		"engine_fuel_type":            "Petrol",
		"engine_max_power":            "105 hp @ 6000 rpm",
		"engine_max_torque":           "150 Nm @ 4500 rpm",
		"engine_fuel_supply_system":   "MPFI",
		"engine_bore_stroke":          "74.0 x 86.6 mm",
		"engine_compression_ratio":    "10.5:1",
		"engine_turbo_charger":        "No",
		"engine_super_charger":        "No",
		"transmission_type":           "Manual",
		"transmission_gearbox":        "5-Speed",
		"transmission_drive_type":     "FWD",
		"transmission_clutch_type":    "Single Plate Dry Clutch",
		"performance_top_speed":       "170 km/h",
		"performance_acceleration":    "10.9 seconds",
		"performance_mileage_arai":    "18 km/L",
		"performance_mileage_city":    "15 km/L",
		"performance_mileage_highway": "20 km/L",
		"performance_emission_norm":   "BS VI",
		"dimensions_length":           "4314 mm",
		"dimensions_width":            "1809 mm",
		"dimensions_height":           "1636 mm",
		"dimensions_wheelbase":        "2585 mm",
		"dimensions_front_tread":      "1521 mm",
		"dimensions_rear_tread":       "1524 mm",
		"dimensions_ground_clearance": "177 mm",
		"dimensions_boot_space":       "378 L",
		"dimensions_fuel_tank":        "48 L",
		"dimensions_turning_radius":   "5.6 m",
		"weight_kerb_weight":          "1195 kg",
		"weight_gross_weight":         "1695 kg",
		"capacity_seating_capacity":   "5",
		"capacity_doors":              "5",
		"suspension_front":            "MacPherson Strut",
		"suspension_rear":             "Torsion Beam",
		"brakes_front":                "Disc",
		"brakes_rear":                 "Drum",
		"tyres_size":                  "195/60 R16",
		"tyres_wheel_size":            "16 inches",
		"tyres_spare_size":            "195/60 R16",
		"exterior_colors":             "Arctic White, Black, Gray, Silver, Blue, Red",
		"exterior_headlights":         "Halogen",
		"exterior_daytime_running":    "LED DRLs",
		"exterior_roof_rails":         "Yes",
		"exterior_wheels":             "16-inch Alloy Wheels",
		"interior_seats_material":     "Fabric",
		"interior_seats_adjustment":   "6-way Manual",
		"interior_ac":                 "Manual AC",
		"infotainment_screen_size":    "7-inch Touchscreen",
		"infotainment_connectivity":   "Android Auto, Apple CarPlay, Bluetooth",
		"infotainment_speakers":       "4 Speakers",
		"safety_airbags":              "Front Airbags",
		"safety_abs":                  "Yes",
		"safety_ebd":                  "Yes",
		"safety_brake_assist":         "Yes",
		"safety_esp":                  "Yes",
		"safety_parking_sensors":      "Rear Parking Sensors",
		"safety_camera":               "Rear Parking Camera",
		"features_central_locking":    "Yes",
		"features_keyless_entry":      "Yes",
		"features_push_start":         "Yes",
		"features_cruise_control":     "No",
		"features_sunroof":            "No",
		"year":                        "2020",
		"category":                    "SUV",
		"subcategory":                 "Subcompact SUV",
	}

	// Create specifications
	for key, value := range specifications {
		if specKeyID, exists := specKeyMap[key]; exists {
			spec := models.SpecificationModel{
				ProductID:          product.ID,
				SpecificationKeyID: specKeyID,
				Value:              value,
				Status:             1,
			}
			if err := db.Create(&spec).Error; err != nil {
				log.Printf("Error creating specification for key %s: %v", key, err)
				continue
			}

			// Create translation
			translation := models.SpecificationTranslationModel{
				SpecificationID: spec.ID,
				LanguageCode:    "bn",
				Value:           mzs.getBanglaTranslations()[value],
				Status:          1,
			}
			if err := db.Create(&translation).Error; err != nil {
				log.Printf("Error creating translation for specification %d: %v", spec.ID, err)
			}
		} else {
			log.Printf("Specification key not found: %s", key)
		}
	}

	log.Printf("Seeded specifications for MG ZS")
	return nil
}
